// Generated by gencpp from file IRIS24/BS2PC.msg
// DO NOT EDIT!


#ifndef IRIS24_MESSAGE_BS2PC_H
#define IRIS24_MESSAGE_BS2PC_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace IRIS24
{
template <class ContainerAllocator>
struct BS2PC_
{
  typedef BS2PC_<ContainerAllocator> Type;

  BS2PC_()
    : status(0)
    , tujuan_x(0)
    , tujuan_y(0)  {
    }
  BS2PC_(const ContainerAllocator& _alloc)
    : status(0)
    , tujuan_x(0)
    , tujuan_y(0)  {
  (void)_alloc;
    }



   typedef int8_t _status_type;
  _status_type status;

   typedef int16_t _tujuan_x_type;
  _tujuan_x_type tujuan_x;

   typedef int16_t _tujuan_y_type;
  _tujuan_y_type tujuan_y;





  typedef boost::shared_ptr< ::IRIS24::BS2PC_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::IRIS24::BS2PC_<ContainerAllocator> const> ConstPtr;

}; // struct BS2PC_

typedef ::IRIS24::BS2PC_<std::allocator<void> > BS2PC;

typedef boost::shared_ptr< ::IRIS24::BS2PC > BS2PCPtr;
typedef boost::shared_ptr< ::IRIS24::BS2PC const> BS2PCConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::IRIS24::BS2PC_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::IRIS24::BS2PC_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::IRIS24::BS2PC_<ContainerAllocator1> & lhs, const ::IRIS24::BS2PC_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.tujuan_x == rhs.tujuan_x &&
    lhs.tujuan_y == rhs.tujuan_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::IRIS24::BS2PC_<ContainerAllocator1> & lhs, const ::IRIS24::BS2PC_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace IRIS24

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::IRIS24::BS2PC_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::IRIS24::BS2PC_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::IRIS24::BS2PC_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::IRIS24::BS2PC_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::IRIS24::BS2PC_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::IRIS24::BS2PC_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::IRIS24::BS2PC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b9347be61b65295736981e367dd02681";
  }

  static const char* value(const ::IRIS24::BS2PC_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb9347be61b652957ULL;
  static const uint64_t static_value2 = 0x36981e367dd02681ULL;
};

template<class ContainerAllocator>
struct DataType< ::IRIS24::BS2PC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "IRIS24/BS2PC";
  }

  static const char* value(const ::IRIS24::BS2PC_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::IRIS24::BS2PC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 status\n"
"int16 tujuan_x\n"
"int16 tujuan_y\n"
;
  }

  static const char* value(const ::IRIS24::BS2PC_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::IRIS24::BS2PC_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.tujuan_x);
      stream.next(m.tujuan_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BS2PC_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::IRIS24::BS2PC_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::IRIS24::BS2PC_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int8_t>::stream(s, indent + "  ", v.status);
    s << indent << "tujuan_x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.tujuan_x);
    s << indent << "tujuan_y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.tujuan_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IRIS24_MESSAGE_BS2PC_H
